#!/bin/sh

echo "🧪 Running Flutter unit tests..."

flutter test

# لو فيه أي فشل (exit code != 0) يمنع الكوميت
if [ $? -ne 0 ]; then
  echo "❌ Unit tests failed. Commit aborted."
  exit 1
fi

echo "✅ All unit tests passed!"
